### ISSUE TITLE
Different ip

### ISSUE THREAD

**Issue by dzinks2009** [ronindesign/docker-teamspeak-client#1]
Hi, you said "For generic TeamSpeak 3 client image that does not immediatly connect client".

How would I be able to connect to a different server that's not hosted locally and on a docker?

**Comment by tturnerdev** [comment]
Apologies @dzinks2009 for the slow reply, busy few days!

You should be able to configure the TeamSpeak 3 server's IP in configTS3AudioBot.cfg.
